# -*- coding: utf-8 -*-
"""ListaExecicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ce53r4-7_SceyX0HIJO7z_BkePs5xKXo

1.
"""

nome = input('Digite seu nome: ')
print(f'Olá {nome}!')

nome = input('Digite seu nome: ')
idade = input('Digite sua idade: ')
print(f'Olá {nome}!, voce tem {idade} anos')

nome = input('Digite seu nome: ')
idade = input('Digite sua idade: ')
altura = input('Digite sua altura: ')
print(f'Olá {nome}!, voce tem {idade} anos e mede {altura} metros')

"""2."""

a, b = input('Digite dois numeros: ').split()
a = int(a)
b = int(b)
print(f'A soma de {a} e {b} é {a+b}')

a, b, c = input('Digite tres numeros: ').split()
s = int(a) + int(b) + int(c)
print(f'A soma de {s}')

a, b = input('Digite dois numeros: ').split()
a = int(a)
b = int(b)
print(f'A soma de {a} e {b} é {a-b}')

a, b = input('Digite dois numeros: ').split()
s = int(a) * int(b)
print(s)

a, b = input('Digite dois numeros, o segundo nao deve ser nulo: ').split()
s = int(a) // int(b)
print(s)

a, b = input('Digite dois numeros: ').split()
s = int(a) ** int(b)
print(s)

a, b = input('Digite dois numeros, o segundo nao deve ser nulo: ').split()
s = int(a) % int(b)
print(s)

a, b, c = input('Digite tres notas: ').split()
s = int(a) + int(b) + int(c)
print(f'A soma de {s/3}')

print( (5*1 + 12*2 + 20*3 + 15*4)/4)

"""3."""

frase = 'Sou uma Frase'
frase

frase = input('Digite uma frase: ')
frase

frase = input('Digite uma frase: ')
frase.upper()

frase = input('Digite uma frase: ')
frase.strip()

frase = input('Digite uma frase: ')
frase.strip().lower()

frase = input('Digite uma frase: ')
frase.replace('e','f')

frase = input('Digite uma frase: ')
frase.replace('a','@')

frase = input('Digite uma frase: ')
frase.replace('s','$')

