# -*- coding: utf-8 -*-
"""listaExercicios3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QxxZbYbJ3ovhHJSDq50oZVT2jW8X7yHq

1.
"""

cont = input('entre com dois numeros inteiros: ').split()
cont[0] = int(cont[0])
cont[1] = int(cont[1])

for cont in range(cont[0]+1,cont[1]):
  print(cont)

"""2."""

colA = 4
colB = 10
cont = 1
while colA <= colB:
  colA += colA*0.03
  colB += colB*0.015
  cont += 1

cont

"""3."""

nota = cont = 0
for cont in range(15):
  nota = float(input('entre com um valor: '))
  while (nota < 0) or (nota > 5):
    nota = float(input(f'Nota inválida, insira novamente a nota da pessoa usuária: '))

"""4."""

cont = temp = soma = 0
temp = int(input('insira a temperatura: '))
while temp != -273:
  soma = soma + temp
  cont += 1
  temp = int(input('insira a temperatura: '))

print(f'a media das temperaturas é {soma/cont}')

"""5."""

num = int(input('entre com o numero: '))
cont = 1
fatorial = 1
while cont <= num:
  fatorial = fatorial*cont
  cont += 1

print(fatorial)

"""6."""

num = int(input('tabuada do numero: '))
cont =1
while cont <=10:
  print(f'{cont}x{num}={num*cont}')
  cont +=1

"""7."""

num = int(input('entre com um numero inteiro: '))
flag = True
cont = 2
while cont < num:
  if num%cont == 0:
    flag = False
    break
  cont += 1

if flag == True:
  print('é primo')
else: print('nao é primo')

"""8."""

flag = True

cont1 = cont2 = cont3 = cont4 = 0

while flag == True:
  idade = int(input('sua idade:'))
  if 0 <= idade <= 25:
    cont1 += 1
  elif 25 <= idade <=50:
    cont2 += 1
  elif 51 <= idade <= 75:
    cont3 += 1
  elif 76 <= idade <= 100:
    cont4 += 1
  elif idade < 0:
    flag = False

print(f'{cont1}, {cont2}, {cont3}, {cont4}')

"""9."""

cont1 = cont2 = cont3 = cont4 = contNulo = contBranco =0

for cont in range(1,20):
  voto = int(input('registre seu voto: '))
  if voto == 1:
    cont1 += 1
  elif voto == 2:
    cont2 += 1
  elif voto == 3:
    cont3 += 1
  elif voto == 4:
    cont4 += 1
  elif voto == 5:
    contNulo += 1
  elif voto == 6:
    contBranco +=1

print(f'Numero1: {cont1}, Numero2: {cont2}, Numero3: {cont3}, Numero4: {cont4}, Nulos: {(contNulo/20*100)}%, Branco: {(contBranco/20*100)}%')