# -*- coding: utf-8 -*-
"""ListaExercicios2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKWTLiscaZSFLu9A3rOlwps73jplNcwO

1.
"""

num = input('digite dois numeros').split()
if num[0] > num[1]:
  print(f'{num[0]} é maior que {num[1]}')
elif num[0] < num[1]:
  print(f'{num[1]} é maior que {num[0]}')
elif num[0] == num[1]:
  print('numeros identicos')

"""2."""

perc = input('entre com o percentual de crescimento da empres: ')
perc = perc.replace('%', '')
perc = int(perc)
if perc > 0:
  print('houve crescimento')
elif perc < 0:
  print('houve descrecimento')

"""3."""

vogais = ['a', 'e', 'i', 'o', 'u']
letra = input('digite uma letra:')
if letra in vogais:
  print(f'{letra} é uma vogal')
else: print(f'letra é uma consoante')

"""4.

"""

valores = input('entre com os tres valores dos ultimos anos: ').split()

if valores[0] > valores[1] and valores[2]:
  maior = valores[0]
elif valores[0] < valores[1] and valores[2]:
  menor = valores[0]
elif valores[1] > valores[0] and valores[2]:
  maior = valores[0]
elif valores[1] < valores[0] and valores[2]:
  menor = valores[0]
elif valores[2] > valores[1] and valores[0]:
  maior = valores[0]
elif valores[2] < valores[1] and valores[0]:
  menor = valores[0]

print(f'maior valor: {maior}, menor {menor}')

"""5."""

valores = input('entre com os tres produtos: ').split()

maior = menor = valores[0]

if valores[0] < valores[1] and valores[2]:
  menor = valores[0]
elif valores[1] < valores[0] and valores[2]:
  menor = valores[1]
elif valores[2] < valores[1] and valores[0]:
  menor = valores[2]

menor

"""6."""

valores = input('entre com os tres produtos: ').split()

if (valores[0] >= valores[1]) and (valores[0] >= valores[2]):
    print(valores[0])
    if valores[1] >= valores[2]:
        print(valores[1])
        print(valores[2])
    else:
        print(valores[2])
        print(valores[1])
elif (valores[1] >= valores[0]) and (valores[1] >= valores[2]):
    print(valores[1])
    if valores[0] >= valores[2]:
        print(valores[0])
        print(valores[2])
    else:
        print(valores[2])
        print(valores[0])
else:
    print(valores[2])
    if valores[0] >= valores[1]:
        print(valores[0])
        print(valores[1])
    else:
        print(valores[1])
        print(valores[0])

"""7.

"""

hora = input('entre com o horario que vc estudo: ')

if 'manha' in hora:
  print('Bom dia!')
elif 'tarde' in hora:
  print('Boa tarde!')
elif 'noite' in hora:
  print('Boa noite!')

"""8."""

num = int(input('entre com numero inteiro: '))
if num%2 == 0:
  print(f'{num} é par')
else: print(f'{num} é impar')

"""9."""

num = float(input('Digite um número: '))

# Verificamos se o número é inteiro ou decimal através do resultado do módulo
if num % 1 == 0:
    print('O número é inteiro.')
else:
    print('O número é decimal.')

"""10.

"""

num = input('entre com dois numeros: ').split()
operacao = input('qual operacao: ')
par = pos = dec = 0

if operacao == 'soma':
  res = float(num[0]) + float(num[1])
  if res%2 == 0:
    par = 'par'
  else: par = 'impar'
  if res > 0:
    pos = 'positivo'
  elif res < 0:
    pos = 'negativo'
  else: pos = 'nulo'
  if res% 1 == 0:
    dec = 'inteiro'
  else: dec = 'decimal'

if operacao == 'subtracao':
  res = float(num[0]) - float(num[1])
  if res%2 == 0:
    par = 'par'
  else: par = 'impar'
  if res > 0:
    pos = 'positivo'
  elif res < 0:
    pos = 'negativo'
  else: pos = 'nulo'
  if res% 1 == 0:
    dec = 'inteiro'
  else: dec = 'decimal'

if operacao == 'divisao':
  res = float(num[0]) / float(num[1])
  if res%2 == 0:
    par = 'par'
  else: par = 'impar'
  if res > 0:
    pos = 'positivo'
  elif res < 0:
    pos = 'negativo'
  else: pos = 'nulo'
  if res% 1 == 0:
    dec = 'inteiro'
  else: dec = 'decimal'

if operacao == 'multiplicacao':
  res = float(num[0]) * float(num[1])
  if res%2 == 0:
    par = 'par'
  else: par = 'impar'
  if res > 0:
    pos = 'positivo'
  elif res < 0:
    pos = 'negativo'
  else: pos = 'nulo'
  if res% 1 == 0:
    dec = 'inteiro'
  else: dec = 'decimal'

print(f'o resultado é: {res}, {par}, {pos}, {dec}')

"""11."""

num = input('entre com os tres lados do triangulo: ').split()
num = [int(x) for x in num]
if num[0]+ num[1] >= num[2]:
  if num[0] == num[1] == num[2]:
    print('triangulo equilatero')
  elif num[0] == num[1] or num[0] == num[2] or num[1] == num[2]:
    print('triangulo isoceles')
  elif num[0] != num[1] != num[2]:
    print('triangulo escaleno')
else: print('Nao pode seer um triangulo')

"""12."""

gas = input('qual gasolina (E ou D): ')
litros = float(input('quantos litros: '))
total = 0.0

if gas == 'E':
  if litros > 15:
    total = 1,7*litros - (1.7*litros*0.04)
  else: total = 1,7*litros - (1.7*litros)*0.02

if gas == 'D':
  if litros > 15:
    total = 2.0*litros - (2.0*litros)*0.05
  else: total = 2.0*litros - (2.0*litros)*0.03

print(f'preço é de {total}')

"""13."""

quant1 = input('quantidade de vendas 2022: ')
quant2 = input('quantidade de vendas 2023: ')

var = 100 * (quant2 - quant1) / (quant1)
bonificao = False


if var > 20:
  bonificacao = True
elif 2 < var < 20:
  bonificacao = True
  tam = 'pequena'
elif -10 < var < 2:
  bonificacao = False
else: tam = 'corte de gastos'